MESSAGE_CODE_REGISTRATION = 100
MESSAGE_CODE_NEW_CONNECTION = 101
MESSAGE_CODE_CONNECTION_LOST = 102
MESSAGE_CODE_NEW_CONNECTION_HANDSHAKE = 103
MESSAGE_CODE_NEW_LIVE_NODE = 104
MESSAGE_CODE_LOST_LIVE_NODE = 105
MESSAGE_CODE_GOSSIP = 200


# messages for commands
MESSAGE_CODE_PUT_REQUEST = 300
MESSAGE_CODE_GET_REQUEST = 301
MESSAGE_CODE_PARTITION_REQUEST = 302
MESSAGE_CODE_RESPONSE = 303
